#pragma once

#include "Tests/Logger.h"
#include "Tests/Utils.h"

namespace Tests
{
  //  ConsensusNetwork
  //
  //  Owns N BftConsensus instances and a shared message queue. Each
  //  instance's broadcast callbacks push envelopes into the queue
  //  instead of delivering directly. deliverAll() drains the queue
  //  until it's empty, which settles a full round deterministically.
  //
  //  The network never advances time on its own. Tests drive timers
  //  explicitly via advanceAllTimers().

  class ConsensusNetwork
  {
  public:
    explicit ConsensusNetwork(size_t n, Logging::ILogger &logger)
        : logger_(logger), log_ref_(std::make_unique<Logging::LoggerRef>(logger, "net"))
    {
      validators_.reserve(n);
      for (size_t i = 0; i < n; ++i)
        validators_.push_back(TestValidator::make(static_cast<Id>(i + 1)));

      instances_.reserve(n);
      committed_.resize(n);
      offline_.assign(n, false);
      height_advances_.resize(n);

      for (size_t i = 0; i < n; ++i)
        instances_.push_back(makeInstance(i));
    }

    // ---- Lifecycle ----

    void startAll(Height height)
    {
      for (size_t i = 0; i < instances_.size(); ++i)
      {
        if (!offline_[i])
          instances_[i]->start(height);
      }
      deliverAll();
    }

    void stopAll()
    {
      for (auto &inst : instances_)
        inst->stop();
    }

    // Deliver every queued message, including any messages those
    // deliveries generate, until the queue is empty.
    void deliverAll()
    {
      // Guard against pathological loops; a healthy round settles
      // in far fewer than this.
      constexpr size_t MAX_ROUNDS = 10'000;
      size_t iterations = 0;

      while (!queue_.empty())
      {
        if (++iterations > MAX_ROUNDS)
          throw std::runtime_error("ConsensusNetwork::deliverAll: message loop did not settle");

        Envelope env = queue_.front();
        queue_.pop();

        if (offline_[env.to])
          continue;

        switch (env.kind)
        {
        case Envelope::Proposal:
          instances_[env.to]->onProposal(env.proposal);
          break;
        case Envelope::Prevote:
          instances_[env.to]->onPrevote(env.vote);
          break;
        case Envelope::Precommit:
          instances_[env.to]->onPrecommit(env.vote);
          break;
        case Envelope::Restart:
          instances_[env.to]->start(env.restart_height);
          break;
        }
      }
    }

    size_t totalCommitted() const
    {
      size_t n = 0;
      for (const auto &v : committed_)
        n += v.size();
      return n;
    }

    void advanceAllTimers()
    {
      // Deliver any pending messages FIRST, so that any quorum that's
      // about to form is formed before we fire timers.
      deliverAll();

      // Then fire timers.
      for (size_t i = 0; i < instances_.size(); ++i)
        if (!offline_[i])
          instances_[i]->forceTimerExpiryForTest();

      for (size_t i = 0; i < instances_.size(); ++i)
        if (!offline_[i])
          instances_[i]->pollTimers();

      // Deliver any messages generated by the timer fires.
      deliverAll();
    }

    // advance until a specific condition is met, or fail.
    bool advanceUntil(std::function<bool()> predicate, int max_passes = 16)
    {
      for (int i = 0; i < max_passes; ++i)
      {
        if (predicate())
          return true;
        advanceAllTimers();
      }
      return predicate();
    }

    // ---- Introspection ----

    Consensus::BftConsensus &instance(size_t i) { return *instances_[i]; }

    const std::vector<Core::Block> &committed(size_t i) const
    {
      return committed_[i];
    }

    const std::vector<Height> &heightAdvances(size_t i) const
    {
      return height_advances_[i];
    }

    const TestValidator &validator(size_t i) const
    {
      return validators_[i];
    }

    size_t size() const { return instances_.size(); }

    // ---- Offline control ----

    void setOffline(size_t i, bool offline)
    {
      offline_[i] = offline;
    }

    bool isOffline(size_t i) const { return offline_[i]; }

  private:
    Consensus::Dependencies makeDeps(size_t index)
    {
      Consensus::Dependencies deps;
      deps.my_validator_id = [this, index]() -> Id
      { return validators_[index].id; };
      deps.sign = [this, index](const Crypto::Hash &h) -> Crypto::Signature
      { return validators_[index].sign(h); };
      deps.current_height = []() -> Height
      { return 0; };
      deps.active_set = [this]() -> std::vector<Id>
      {
        std::vector<Id> ids;
        ids.reserve(validators_.size());
        for (const auto &v : validators_)
          ids.push_back(v.id);
        return ids;
      };
      deps.signer_public_key =
          [this](Index idx) -> std::optional<Crypto::PublicKey>
      {
        if (idx >= validators_.size())
          return std::nullopt;
        return validators_[idx].pubkey();
      };
      deps.chain_id = []() -> uint64_t
      { return 0x434C5247; };
      deps.parent_hash = []() -> Crypto::Hash
      { return Crypto::Hash{}; };
      deps.simulate_block =
          [](const Core::Block &b) -> std::optional<Crypto::Hash>
      { return b.header.state_root; };
      deps.my_address = [this, index]() -> Crypto::Address
      { return validators_[index].address; };
      deps.now_ms = [this]() -> uint64_t
      {
        return 1'700'000'000'000ULL + proposed_count_++;
      };
      deps.state_lookup_validator =
          [this](Id id, Core::ValidatorInfo &out) -> bool
      {
        //  The harness doesn't hold a real state DB. Synthesize a
        //  ValidatorInfo whose reward_address matches the validator's
        //  pubkey, so the equivocation proof verifier can check the
        //  signature. Everything else can be default.
        for (const auto &v : validators_)
        {
          if (v.id == id)
          {
            std::memcpy(out.reward_address.data.data(),
                        v.kp.publicKey.data.data(), 32);
            out.id = id;
            out.stake = Core::VALIDATOR_MIN_STAKE;
            out.reward_multiplier = Core::REWARD_MULTIPLIER_START;
            return true;
          }
        }
        return false;
      };
      return deps;
    }

    Consensus::Callbacks makeCallbacks(size_t index)
    {
      Consensus::Callbacks cb;

      cb.broadcast_proposal = [this, index](const Consensus::Proposal &p)
      {
        if (offline_[index])
          return;
        for (size_t to = 0; to < instances_.size(); ++to)
        {
          if (to == index || offline_[to])
            continue;
          Envelope env;
          env.kind = Envelope::Proposal;
          env.to = to;
          env.from = index;
          env.proposal = p;
          queue_.push(std::move(env));
        }
      };

      cb.broadcast_prevote = [this, index](const Consensus::Vote &v)
      {
        if (offline_[index])
          return;
        for (size_t to = 0; to < instances_.size(); ++to)
        {
          if (to == index || offline_[to])
            continue;
          Envelope env;
          env.kind = Envelope::Prevote;
          env.to = to;
          env.from = index;
          env.vote = v;
          queue_.push(std::move(env));
        }
      };

      cb.broadcast_precommit = [this, index](const Consensus::Vote &v)
      {
        if (offline_[index])
          return;
        for (size_t to = 0; to < instances_.size(); ++to)
        {
          if (to == index || offline_[to])
            continue;
          Envelope env;
          env.kind = Envelope::Precommit;
          env.to = to;
          env.from = index;
          env.vote = v;
          queue_.push(std::move(env));
        }
      };

      cb.select_transactions = [](uint64_t, uint64_t)
      { return std::vector<Core::Transaction>{}; };

      cb.on_block_committed = [this, index](const Core::Block &b)
      {
        committed_[index].push_back(b);

        // Mirror production: after a commit, the node poll loop calls
        // start(height+1). The harness does it via a queued envelope so
        // we don't re-enter consensus from its own callback.
        Envelope env;
        env.kind = Envelope::Restart;
        env.to = index;
        env.from = index;
        env.restart_height = b.header.height + 1;
        queue_.push(std::move(env));
      };

      cb.on_height_advanced = [this, index](Height h)
      { height_advances_[index].push_back(h); };

      return cb;
    }

    std::unique_ptr<Consensus::BftConsensus> makeInstance(size_t index)
    {
      return std::make_unique<Consensus::BftConsensus>(
          makeDeps(index),
          makeCallbacks(index),
          Consensus::Config{},
          *log_ref_);
    }

    Logging::ILogger &logger_;
    std::unique_ptr<Logging::LoggerRef> log_ref_;
    std::vector<TestValidator> validators_;
    std::vector<std::unique_ptr<Consensus::BftConsensus>> instances_;
    std::vector<std::vector<Core::Block>> committed_;
    std::vector<std::vector<Height>> height_advances_;
    uint64_t proposed_count_{0};
    std::vector<bool> offline_;
    std::queue<Envelope> queue_;
  };
}