// Copyright (c) 2018-2026 Conceal Network & Conceal Devs
//
// Distributed under the MIT/X11 software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#pragma once

#include <array>
#include <cstddef>

namespace Wallet
{
  //  BIP-39 English wordlist
  //
  //  The canonical 2048-word list from BIP-39. Public domain; the
  //  list was constructed by the BIP-39 authors through a documented
  //  process, and is reproduced here verbatim.
  //
  //  Do NOT edit this list. If a word needs to change, that means the
  //  upstream BIP changed, which means we need to think about
  //  compatibility with mnemonics generated by other wallets.
  //
  //  Tests in Tests/Wallet/Bip39.cpp verify the list against its
  //  canonical SHA-256 hash. If the list is ever corrupted, tests fail
  //  loudly.
  //
  //  Index in this array IS the word's 11-bit value in a mnemonic.
  //  Word at index 0 is "abandon", index 1 is "ability", and so on.

  inline constexpr size_t BIP39_WORDLIST_SIZE = 2048;

  extern const std::array<const char *, BIP39_WORDLIST_SIZE> BIP39_ENGLISH;

} // namespace Wallet