// Copyright (c) 2018-2026 Conceal Network & Conceal Devs
//
// Distributed under the MIT/X11 software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <gtest/gtest.h>

#include "Crypto/X25519.h"

#include <array>
#include <cstring>
#include <set>

using namespace Crypto;

// ---------------------------------------------------------------------------
//  Key generation
// ---------------------------------------------------------------------------

TEST(Crypto_X25519, GenerateKeyPairProducesDistinctKeys)
{
  // CSPRNG output, so two consecutive calls produce different secrets.
  // The probability of collision is 2^-256; this test failing would
  // indicate a broken CSPRNG, not a flaky test.
  auto a = generateX25519KeyPair();
  auto b = generateX25519KeyPair();

  EXPECT_NE(std::memcmp(a.secretKey.data(), b.secretKey.data(), 32), 0);
  EXPECT_NE(std::memcmp(a.publicKey.data(), b.publicKey.data(), 32), 0);
}

TEST(Crypto_X25519, GeneratedPublicKeyMatchesDerivation)
{
  // The public key generated by generateX25519KeyPair must equal the
  // public key derived from the secret via x25519PublicKey. If
  // generateX25519KeyPair ever pre-clamps or post-processes the secret
  // in a way that diverges from x25519PublicKey, this catches it.
  auto kp = generateX25519KeyPair();

  std::array<uint8_t, 32> derived{};
  x25519PublicKey(kp.secretKey.data(), derived.data());

  EXPECT_EQ(std::memcmp(kp.publicKey.data(), derived.data(), 32), 0);
}

TEST(Crypto_X25519, PublicKeyDerivationIsDeterministic)
{
  // Fixed secret, repeated derivation, same output. Pins the wrapper
  // to Monocypher's deterministic behavior.
  std::array<uint8_t, 32> sk{};
  for (size_t i = 0; i < 32; ++i)
    sk[i] = static_cast<uint8_t>(i);

  std::array<uint8_t, 32> pk1{};
  std::array<uint8_t, 32> pk2{};
  x25519PublicKey(sk.data(), pk1.data());
  x25519PublicKey(sk.data(), pk2.data());

  EXPECT_EQ(std::memcmp(pk1.data(), pk2.data(), 32), 0);
}

// ---------------------------------------------------------------------------
//  Scalar multiplication
// ---------------------------------------------------------------------------

TEST(Crypto_X25519, SharedSecretIsSymmetric)
{
  // The core ECDH property: X25519(a_sk, b_pk) == X25519(b_sk, a_pk).
  // If this fails, the entire session encryption design is broken.
  auto a = generateX25519KeyPair();
  auto b = generateX25519KeyPair();

  std::array<uint8_t, 32> ab{};
  std::array<uint8_t, 32> ba{};

  ASSERT_TRUE(x25519(a.secretKey.data(), b.publicKey.data(), ab.data()));
  ASSERT_TRUE(x25519(b.secretKey.data(), a.publicKey.data(), ba.data()));

  EXPECT_EQ(std::memcmp(ab.data(), ba.data(), 32), 0);
}

TEST(Crypto_X25519, SharedSecretIsNotAllZeros)
{
  // For well-formed keys, the shared secret must not be zero.
  auto a = generateX25519KeyPair();
  auto b = generateX25519KeyPair();

  std::array<uint8_t, 32> shared{};
  ASSERT_TRUE(x25519(a.secretKey.data(), b.publicKey.data(), shared.data()));

  std::array<uint8_t, 32> zero{};
  EXPECT_NE(std::memcmp(shared.data(), zero.data(), 32), 0);
}

TEST(Crypto_X25519, LowOrderPublicKeyIsRejected)
{
  // The all-zeros public key is the identity point. X25519 with any
  // secret against it produces a zero shared secret. The wrapper must
  // detect this and return false.
  auto kp = generateX25519KeyPair();

  std::array<uint8_t, 32> zero_pk{};
  std::array<uint8_t, 32> out{};

  EXPECT_FALSE(x25519(kp.secretKey.data(), zero_pk.data(), out.data()));

  // On failure, out must be zeroed — not left uninitialized, not
  // containing the raw zero shared secret (which is the same thing
  // here, but the contract is: out is never a value the caller should
  // use after a false return).
  std::array<uint8_t, 32> zero{};
  EXPECT_EQ(std::memcmp(out.data(), zero.data(), 32), 0);
}

TEST(Crypto_X25519, LowOrderPublicKeyOneIsRejected)
{
  // The public key with a single 1 in the low byte is another
  // well-known low-order point. It must also be rejected.
  auto kp = generateX25519KeyPair();

  std::array<uint8_t, 32> low_order_pk{};
  low_order_pk[0] = 1;

  std::array<uint8_t, 32> out{};
  EXPECT_FALSE(x25519(kp.secretKey.data(), low_order_pk.data(), out.data()));
}

TEST(Crypto_X25519, OutputIsWrittenOnSuccess)
{
  // A successful x25519 must write to out. A wrapper that forgot the
  // memcpy on the success path would leave out at its initial value;
  // this test catches that.
  auto a = generateX25519KeyPair();
  auto b = generateX25519KeyPair();

  std::array<uint8_t, 32> out{};
  out.fill(0xAA); // sentinel

  ASSERT_TRUE(x25519(a.secretKey.data(), b.publicKey.data(), out.data()));

  // The output must have changed from the sentinel.
  std::array<uint8_t, 32> sentinel{};
  sentinel.fill(0xAA);
  EXPECT_NE(std::memcmp(out.data(), sentinel.data(), 32), 0);
}

// ---------------------------------------------------------------------------
//  Randomized smoke test
// ---------------------------------------------------------------------------

TEST(Crypto_X25519, ManyRandomKeyPairsAllAgree)
{
  // 100 keypairs, all pairwise symmetric. Catches rare edge cases that
  // a single fixed vector wouldn't.
  std::vector<X25519KeyPair> kps;
  for (int i = 0; i < 100; ++i)
    kps.push_back(generateX25519KeyPair());

  for (size_t i = 0; i < kps.size(); ++i)
  {
    for (size_t j = i + 1; j < kps.size(); ++j)
    {
      std::array<uint8_t, 32> ij{};
      std::array<uint8_t, 32> ji{};
      ASSERT_TRUE(x25519(kps[i].secretKey.data(), kps[j].publicKey.data(), ij.data()));
      ASSERT_TRUE(x25519(kps[j].secretKey.data(), kps[i].publicKey.data(), ji.data()));
      EXPECT_EQ(std::memcmp(ij.data(), ji.data(), 32), 0);
    }
  }
}