// Copyright (c) 2018-2026 Conceal Network & Conceal Devs
//
// Distributed under the MIT/X11 software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#pragma once

#include <cstdint>
#include <string_view>

namespace Core
{
  //  Transaction type
  //
  //  Grouped by category so related types share a byte range. This leaves
  //  room for future expansion without renumbering anything.
  //
  //  Ranges:
  //    0x00 - 0x0F: Core (transfers)
  //    0x10 - 0x1F: Staking
  //    0x20 - 0x2F: Validator
  //    0x30 - 0x3F: AMM
  //    0x40 - 0x4F: DEX / Orders
  //    0x50 - 0x5F: Token management
  //    0x60 - 0x6F: Governance (reserved)
  //    0x70 - 0x7F: Cross-chain (reserved)
  //    0xF0 - 0xFE: System (implicit, generated by the chain)
  //    0xFF:        Invalid sentinel (never on-chain)
  //
  //  NEVER reuse a value. If a type is removed, leave a gap.

  enum class TxType : uint8_t
  {
    // ---- Core (0x00 - 0x0F) ----
    Transfer = 0x00,

    // ---- Staking (0x10 - 0x1F) ----
    OptInStaking = 0x10,
    OptOutStaking = 0x11,
    ClaimRewards = 0x12,

    // ---- Validator (0x20 - 0x2F) ----
    RegisterValidator = 0x20,
    UnregisterValidator = 0x21,
    UpdateRewardAddress = 0x22,

    // ---- AMM (0x30 - 0x3F) ----
    CreatePool = 0x30,
    AddLiquidity = 0x31,
    RemoveLiquidity = 0x32,
    Swap = 0x33,

    // ---- DEX / Orders (0x40 - 0x4F) ----
    CreateOrder = 0x40,
    CancelOrder = 0x41,

    // ---- Token management (0x50 - 0x5F) ----
    CreateToken = 0x50,
    MintToken = 0x51,
    BurnToken = 0x52,
    UpdateTokenMeta = 0x53,

    // ---- Governance (0x60 - 0x6F) ----
    // Reserved for future use.

    // ---- Cross-chain (0x70 - 0x7F) ----
    // Reserved for future use.

    // ---- System (0xF0 - 0xFE) ----
    BlockReward = 0xF0,  // implicit, generated by consensus
    OrderExpired = 0xF1, // implicit, generated by order engine
    Slash = 0xF2,        // implicit, generated by consensus

    // ---- Sentinels ----
    Invalid = 0xFF,
  };

  // True if this type can be submitted by users.
  // System types (0xF0+) are generated by the chain itself.
  constexpr bool isUserSubmitted(TxType t) noexcept
  {
    return static_cast<uint8_t>(t) < 0xF0;
  }

  // True if this type is generated by the chain, not a user.
  constexpr bool isSystemTx(TxType t) noexcept
  {
    return static_cast<uint8_t>(t) >= 0xF0 && t != TxType::Invalid;
  }

  // Human-readable name for logging and error messages.
  std::string_view txTypeName(TxType t) noexcept;

} // namespace Core